-- 1. Mood Entries
CREATE TABLE mood_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  date TEXT, -- For frontend display format, e.g. "Mon, May 5"
  time TEXT, -- e.g. "4:01 PM"
  emoji TEXT,
  level INTEGER, -- Mood level from 1-5
  detailed_score INTEGER, -- Original score from 0-10
  tags TEXT[], -- Store category tags as array
  note TEXT,
  suggestion TEXT,
  is_locked BOOLEAN DEFAULT FALSE,
  secure_note TEXT,
  pin TEXT,
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 2. Assessments (Stress/Health Assessments)
CREATE TABLE assessments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  type TEXT,
  date TIMESTAMPTZ DEFAULT NOW(),
  score FLOAT,
  total_score INTEGER,
  question_count INTEGER,
  severity TEXT,
  answers INTEGER[], -- Store answer indexes
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 3. Journal Entries
CREATE TABLE journal_entries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  content TEXT,
  date TIMESTAMPTZ DEFAULT NOW(),
  mood TEXT,
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
  is_collected BOOLEAN DEFAULT FALSE
);

-- 4. Reminders
CREATE TABLE reminders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT,
  time TEXT,
  active BOOLEAN DEFAULT TRUE,
  icon TEXT,
  color TEXT,
  freq TEXT,
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 5. Companion Messages (AI Chat History)
CREATE TABLE companion_messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  role TEXT, -- 'user' or 'assistant'
  content TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 6. Sound Mixes (White Noise Mixes)
CREATE TABLE mixes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  volumes JSONB, -- Store sound source volumes, e.g. {"rain":50,"lofi":30}
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 7. Kit Notes
CREATE TABLE kit_notes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content TEXT,
  date TEXT,
  user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 8. User Settings
CREATE TABLE settings (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) DEFAULT auth.uid(),
  name TEXT DEFAULT 'User',
  dark_mode BOOLEAN DEFAULT FALSE,
  notifications BOOLEAN DEFAULT TRUE,
  language TEXT DEFAULT 'English (US)'
);

-- Enable Row Level Security (RLS)
-- Ensures users can only access and manage their own data
ALTER TABLE mood_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE companion_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE mixes ENABLE ROW LEVEL SECURITY;
ALTER TABLE kit_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
CREATE POLICY "Users can manage their own mood entries"
ON mood_entries
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own assessments"
ON assessments
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own journal entries"
ON journal_entries
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own reminders"
ON reminders
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own companion messages"
ON companion_messages
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own mixes"
ON mixes
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own kit notes"
ON kit_notes
FOR ALL
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own settings"
ON settings
FOR ALL
USING (auth.uid() = user_id);